# Generated by Django 5.1.1 on 2024-10-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('client_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('employee_availability', models.CharField(blank=True, max_length=100, null=True)),
                ('service_catalog', models.CharField(choices=[('Brazilian', 'Brazilian'), ('Haircolor', 'Haircolor'), ('Haircut', 'Haircut')], default='Brazilian', max_length=50)),
                ('service_category', models.CharField(choices=[('Hair Care', 'Hair Care')], default='Hair Care', max_length=50)),
            ],
        ),
    ]
