# Generated by Django 5.1.1 on 2024-10-05 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='service_category',
        ),
    ]
